# Generated by Django 6.0.1 on 2026-01-29 01:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_date', models.DateField(auto_now_add=True)),
                ('incident_time', models.TimeField(auto_now_add=True)),
                ('confidence', models.FloatField()),
                ('predicted_class', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidents', to='accounts.myuser')),
            ],
        ),
    ]
